services:
  database:
    image: postgres:18.4-alpine
    container_name: gatekeeper_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-gatekeeper_db}
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-adminpassword}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - gatekeeper_net

  mqtt-broker:
    image: eclipse-mosquitto:2.1.2-alpine
    container_name: gatekeeper_mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - gatekeeper_net

  back-end:
    build:
      context: .
      target: run
    container_name: gatekeeper_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
      - mqtt-broker
    env_file:
      - .env.production # Usa o arquivo de produção por padrão quando o perfil 'prod' está ativo
    environment:
      # Sobrescreve as URLs para usar os nomes dos contêineres na rede do Docker,
      # garantindo a comunicação interna.
      DB_URL: jdbc:postgresql://database:5432/${DB_NAME}
      MQTT_BROKER_URL: tcp://mqtt-broker:1883
    profiles:
      - prod
    networks:
      - gatekeeper_net

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:

networks:
  gatekeeper_net:
    driver: bridge
